services:
  postgres:
    image: postgres:18-alpine
    container_name: modelops-postgres
    restart: unless-stopped 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - modelops-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8-alpine
    container_name: modelops-redis
    restart: unless-stopped 
    ports:
      - "6380:6379"
    volumes:
      - modelops-redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10


  model-server:
    build:
      context: .
      dockerfile: model_server/Dockerfile
    container_name: modelops-model-server
    restart: unless-stopped
    environment:
      MLFLOW_TRACKING_URI: http://host.docker.internal:5000
      MODEL_NAME: demo-classifier
      MODEL_VERSION: "5"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8003:8000"
    volumes:
      - ./mlruns:/home/shekhar/ai-modelops-platform/mlruns:ro

volumes:
  modelops-postgres-data:
  modelops-redis-data:
